// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thoyedmdvmclqxzrhqjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRob3llZG1kdm1jbHF4enJocWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNzc3ODksImV4cCI6MjA4ODg1Mzc4OX0.BfdztPwZf60qoFT7b2xySSkQ1w2vzZ-P2qiXhR2DHls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});